# action.yml
name: 'Coveralls GitHub Action'
description: 'Send test coverage data to Coveralls.io for analysis, change tracking, and notifications.'
author: 'Nick Merwin (Coveralls, Inc.)'
inputs:
  github-token:
    description: 'Put secrets.GITHUB_TOKEN here'
    required: false
    default: ${{ github.token }}
  path-to-lcov:
    description: 'Path to lcov file [DEPRECATED]'
    required: false
  file:
    description: 'Coverage file'
    required: false
  flag-name:
    description: 'Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.'
    required: false
  parallel:
    description: 'Set to true if you are running parallel jobs, then use "parallel-finished: true" for the last action.'
    required: false
  parallel-finished:
    description: 'Set to true for the last action when using "parallel: true".'
    required: false
  carryforward:
    description: 'Comma separated flags used to carryforward results from previous builds if some of the parallel jobs are missing.'
    required: false
  coveralls-endpoint:
    description: 'Coveralls Enterprise server (more info: https://enterprise.coveralls.io)'
    required: false
    default: 'https://coveralls.io'
  base-path:
    description: 'The root folder of the project that originally ran the tests'
    required: false
  git-branch:
    description: 'Override the branch name'
    required: false
  git-commit:
    description: 'Override the commit sha'
    required: false
  debug:
    description: 'Enable debug output'
    required: false
    default: false
outputs:
  coveralls-api-result:
    description: 'Result status of Coveralls API post.'
branding:
  color: 'green'
  icon: 'percent'
runs:
  using: 'composite'
  steps:
    - name: Install coveralls reporter (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew tap coverallsapp/coveralls --quiet
        brew install coveralls --quiet

    - name: Install coveralls reporter (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar xz -C /usr/local/bin

    - name: Install coveralls reporter (Windows)
      if: startsWith(runner.os, 'Windows')
      shell: bash
      run: |
        mkdir -p ~/bin/
        curl -sL https://github.com/mrexox/coverage-reporter/releases/download/v0.1.11/coveralls-windows.zip | zcat > ~/bin/coveralls.exe
        echo ~/bin >> $GITHUB_PATH

    - name: Done report
      if: inputs.parallel-finished == 'true'
      shell: bash
      run: coveralls --done ${{ inputs.debug == 'true' && '--debug' || '' }}
      env:
        COVERALLS_DEBUG: ${{ inputs.debug }}
        COVERALLS_CARRYFORWARD_FLAGS: ${{ inputs.carryforward }}
        COVERALLS_FLAG_NAME: ${{ inputs.flag-name }}
        COVERALLS_PARALLEL: ${{ inputs.parallel }}
        COVERALLS_ENDPOINT: ${{ inputs.coveralls-endpoint }}
        COVERALLS_GIT_BRANCH: ${{ inputs.git-branch }}
        COVERALLS_GIT_COMMIT: ${{ inputs.git-commit }}
        COVERALLS_REPO_TOKEN: ${{ inputs.github-token }}

    - name: Coverage report
      if: inputs.parallel-finished != 'true'
      shell: bash
      run: >-
        coveralls
        ${{ inputs.debug == 'true' && '--debug' || '' }}
        ${{ inputs.base-path && format('--base-path {0}', inputs.base-path) || '' }}
        ${{ (inputs.file || inputs.path-to-lcov) && format('--file {0}', inputs.file || inputs.path-to-lcov) || '' }}
      env:
        COVERALLS_DEBUG: ${{ inputs.debug }}
        COVERALLS_CARRYFORWARD_FLAGS: ${{ inputs.carryforward }}
        COVERALLS_FLAG_NAME: ${{ inputs.flag-name }}
        COVERALLS_PARALLEL: ${{ inputs.parallel }}
        COVERALLS_ENDPOINT: ${{ inputs.coveralls-endpoint }}
        COVERALLS_GIT_BRANCH: ${{ inputs.git-branch }}
        COVERALLS_GIT_COMMIT: ${{ inputs.git-commit }}
        COVERALLS_REPO_TOKEN: ${{ inputs.github-token }}
