name: main

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Rebuild the dist/ directory
        run: npm run build
